import type { BabelDocConfig } from '@/types/config';

export const defaultConfig: BabelDocConfig = {
  langIn: 'en',
  langOut: 'zh',
  pages: '',

  openaiModel: 'gpt-4o-mini',
  openaiBaseUrl: 'https://api.openai.com/v1',
  openaiApiKey: '',
  customSystemPrompt: '',
  enableJsonModeIfRequested: false,
  sendDashscopeHeader: false,
  noSendTemperature: false,
  openaiReasoning: '',

  autoExtractGlossary: true,
  saveAutoExtractedGlossary: true,
  useIndependentTermModel: false,
  openaiTermExtractionModel: '',
  openaiTermExtractionBaseUrl: '',
  openaiTermExtractionApiKey: '',
  openaiTermExtractionReasoning: '',

  outputMode: 'dual_and_mono',
  watermarkOutputMode: 'watermarked',
  useAlternatingPagesDual: false,
  dualTranslateFirst: false,
  onlyIncludeTranslatedPage: false,
  primaryFontFamily: null,

  skipClean: false,
  disableRichTextTranslate: false,
  enhanceCompatibility: false,
  mergeAlternatingLineNumbers: true,
  splitShortLines: false,
  shortLineSplitFactor: 0.8,
  minTextLength: 5,
  skipFormRender: false,
  skipCurveRender: false,
  enableGraphicElementProcess: true,
  formularFontPattern: '',
  formularCharPattern: '',
  addFormulaPlaceholdHint: false,
  disableSameTextFallback: false,
  removeNonFormulaLines: false,
  nonFormulaLineIouThreshold: 0.9,
  figureTableProtectionThreshold: 0.9,
  skipFormulaOffsetCalculation: false,

  ocrWorkaround: false,
  autoEnableOcrWorkaround: false,
  skipScannedDetection: false,

  qps: 4,
  poolMaxWorkers: null,
  termPoolMaxWorkers: null,
  maxPagesPerPart: null,
  reportInterval: 0.1,

  debug: false,
  skipTranslation: false,
  onlyParseGeneratePdf: false,
  ignoreCache: false,
  translateTableText: false,
  showCharBox: false,
};
